try {
  console.log("here is error");
  console.log(x);
  console.log("checking this");
} catch (error) {
  console.log(error);
  console.log("the error occured");
} finally {
  console.log("this will always be executed");
}
